<?php
	$currentUrl = $block->getUrl('*/*/*', ['_current' => true, '_use_rewrite' => true]);
    $currentUrl = $block->escapeUrl($currentUrl);
?>
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_GB/sdk.js#xfbml=1&version=v2.8";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<script
    type="text/javascript"
    async defer
    src="//assets.pinterest.com/js/pinit.js"
></script>
<script src="https://apis.google.com/js/platform.js" async defer>
  {lang: 'en-GB'}
</script>
<?php if ($block->showFacebook()):?>
    <div class="fb-like" data-href="<?php echo $currentUrl ?>" data-layout="button" data-action="like" data-show-faces="true" data-share="true"></div>
<?php endif ?>
<?php if ($block->showTwitter()):?>
    <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
<?php endif ?>
<?php if ($block->showPinterest()):?>
    <a data-pin-do="buttonBookmark" href="https://www.pinterest.com/pin/create/button/"></a>
<?php endif ?>
<?php if ($block->showGPlus()):?>
    <div class="g-plusone" data-size="medium" data-annotation="none"></div>
<?php endif ?>
